### ISSUE TITLE
Troubleshooting on OSX

### ISSUE THREAD

**Issue by sosedoff** [warmans/go-thr#1]
Hi Stefan,

Very cool project - im basically hacking on the same thing, trying to figure out the MIDI messages going in and out of THR10II, their format, etc etc.
I also happen to do that in Go, although using a slightly different setup: gousb for USB comms / gomidi for MIDI.

So far i've done:

- Since im on OSX Catalina i had to use Wireshark and disable SIP (system integrity protection) for USB capture.
- I can monitor MIDI messages from the THR (using go code/with third party commands)
- Identified some of the start-up messages (to enable monitoring)

One issue though: when i attempt to write to THR, it would crash right away (power goes out, need to turn it on manually). Wonder if you've run into something similar?

Gousb project also provides a `lsusb` command that's not available on OSX. Here's an output:

```
020.002 0499:7181 Unknown (Yamaha Corp.)
  Protocol: (Defined at Interface level)
  Configuration 1:
    --------------
    Interface 0 alternate setting 0 (available endpoints: [])
      Audio (Control Device)
    --------------
    Interface 1 alternate setting 0 (available endpoints: [0x02(2,OUT) 0x82(2,IN)])
      Audio (MIDI Streaming)
      ep #2 OUT (address 0x02) bulk [64 bytes]
      ep #2 IN (address 0x82) bulk [64 bytes]
    --------------
    Interface 2 alternate setting 0 (available endpoints: [])
      Audio (Control Device)
    --------------
    Interface 3 alternate setting 0 (available endpoints: [])
      Audio (Streaming)
    Interface 3 alternate setting 1 (available endpoints: [0x83(3,IN)])
      Audio (Streaming)
      ep #3 IN (address 0x83) isochronous - asynchronous undefined usage [196 bytes]
    --------------
    Interface 4 alternate setting 0 (available endpoints: [])
      Audio (Streaming)
    Interface 4 alternate setting 1 (available endpoints: [0x04(4,OUT) 0x84(4,IN)])
      Audio (Streaming)
      ep #4 OUT (address 0x04) isochronous - asynchronous data [196 bytes]
      ep #4 IN (address 0x84) isochronous - unsynchronized undefined usage [4 bytes]
    --------------
```

I've tried to use your project to compare and see what im doing wrong - couple of things i've noticed:

- Monitoring does not work unless the Editor app is open. Seems like the startup message does not trigger the monitoring mode any more. Listen example works only after editor has been opened for the first time. Does not work on its own.
- Preset switching does nothing at all - ie with/without editor it does not change the current preset and gets no messages in response.

Im running THR with 1.40 firmware.  

Just wanted to share this in case if you had any ideas.

**Comment by warmans** [comment]
Hi - nice to hear someone else working on this problem.

Regarding issue 1 (crashing): I saw the same behavior when I tried to write bytes directly over USB instead of using a USB midi client library. But since the amp is just a MIDI device I gave up on that pretty quickly and just used libmidi (or whatever) instead and it stopped crashing.

I can also confirm that the library no longer works (I assume I am also running latest firmware), which is annoying. I could look into it, but I'd just need to look at what the desktop app is doing in wireshark and try and see what changed. It could just be that the commands include the expected amp version in the payload to prevent app/amp version mismatches or something - which would probably be quite obvious in the data.

I had an idea previously which I never explored fully, but it might be something you would want to look into - basically all the official apps (desktop, mobile) are just a wrapper around a single binary library called the "engine" (i.e. a dll on windows and .so on linux). On the one hand this is annoying, because it means you can't just decompile the andoid app and see how all the sysex stuff works, but on the other hand I suppose it would be possible to just write some kind of cgo binding (using the c# code as a reference) for this library and then all the functions of the amp could be controlled with this higher level, less volatile interface. IIRC the android app contains both the ARM binary but also other distributions (probably by accident - e.g. a  x86 llinux version). I have no experience doing this, so I never went any further with it. Also I'm not sure if Yamaha would want anyone publishing code based on their files - but it's an idea.

**Comment by sosedoff** [comment]
Yeah, interesting concept. Here's the libnative.so symbol list dump: https://gist.github.com/sosedoff/f2a643a4276079a203b00a3caf428855

**Comment by sosedoff** [comment]
Cant seem to find the right messages to get it to work again. I was able to capture the sequence message sent by the THR app:

```
f07e7f0601f7
f000010c24004d000000000700010000000000000000000000000000f7
f000010c24004d0002000003105c610679000000f7
f000010c24004d010000000700010000000000000000000000000000f7
f000010c24004d010100000700050000000000000000000000000000f7
f000010c24004d0003000007000f0000000000000000000000000000f7
f000010c24004d010200000b000c0000000400003c007f7f7f7f0000f7
f000010c24004d00050000030000000000000000f7
f000010c24004d0007000007787f7f7f7f4f01000000000000000000f7
f000010c24004d010300000b00060000000400000000000000000000f7
f000010c24004d010400000b00060000000400000000010000000000f7
f000010c24004d010500000b00060000000400000000020000000000f7
f000010c24004d010600000b00060000000400000000030000000000f7
f000010c24004d0009000003000b000000000000f7
```

Im attaching the wireshark pcap file:
[yamaha_init_1.40.0a.pcapng.zip](https://github.com/warmans/go-thr/files/6290866/yamaha_init_1.40.0a.pcapng.zip)

to see the list of outgoing sysex messages use the filter:

```
filter: (usb.darwin.endpoint_address == 0x02) && (sysex)
```

Let me know if you find anything! im going to keep digging
